version: '3.9'
services:
  db: 
    image: 'postgis/postgis:16-3.4'
    container_name: apis_eb_db
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=click123
      - POSTGRES_DB=ecommerce_be
    volumes:
      - 'apis_postgres_data_eb:/var/lib/postgresql'

  redis:
    container_name: apis_eb_redis
    image: 'bitnami/redis:latest'
    ports:
      - 6380:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'apis_redis_data_eb:/bitnami'    

volumes:
    apis_postgres_data_eb:
        external: true
    apis_redis_data_eb:
        external: true    


