version: '3.9'
services:
  db: 
    image: 'mysql'
    container_name: apis_eb_db
    ports:
      - 3306:3307
    environment: 
      - MYSQL_ROOT_PASSWORD=mydb 
      - MYSQL_DATABASE=ecommerce_be
      - MYSQL_TCP_PORT=3307
    volumes:
      - 'apis_mysql_data_eb:/var/lib/mysql'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=apis_eb_db
      - PMA_PORT=3307    

  redis:
    container_name: apis_eb_redis
    image: 'bitnami/redis:latest'
    ports:
      - 6380:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'apis_redis_data_eb:/bitnami'    

volumes:
    apis_mysql_data_eb:
        external: true
    apis_redis_data_eb:
        external: true    


